export const Flag = {
  OPENCODE_DISABLE_MOUSE: false,
  OPENCODE_DISABLE_TERMINAL_TITLE: false,
  OPENCODE_SHOW_TTFD: false,
  OPENCODE_EXPERIMENTAL_WORKSPACES: false,
  OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT: false,
} as const
